namespace AudioManager
{
    public enum AudioClips
    {
        AnvilHit,
        AnvilFall,
        BirdSound,
        Wind,
        SharkJump,
        SharkFall,
        Rain,
        Thunder,
        UfoShip,
        Cow,
        Kick,
        PianoHit,
        PlayerFallIntoWater,
        Cannon,
        BeaverCut,
        Beaver,
        Pig,
        UfoKidnapping,
        BananaSlip,
        Sharknado,
        SharkHit,
        FruitHit,
        BeaverKickScream,
        SprintSteps,
        WalkingSteps,
        Explosion,
        UfoDeath,
        PlayerHit,
    }
}
